config/routes.rb
Rails.application.routes.draw do
  resources :vechicle_params
  resources :vechicle_param_types
  resources :vechicle_fuels
  resources :vechicle_costs
  resources :vechicle_notes
  resources :vechicles
  resources :roles
  devise_for :users

  get 'pages/home'
  get 'pages/about'
  get 'admin/main'
  get 'admin/users'
  get 'stats/vechicles'
  get 'stats/costs'
  get 'stats/fuel'
  get 'stats/main'

  root 'pages#home'

  scope "vechicle" do
    resources :vechicles do
      member do
        get 'vechicle_parameters'
        get 'vechicle_fuels'
        get 'vechicle_costs'
      end
    end
  end

  scope "admin" do
    resources :users do
      member do
        delete 'destroy'
        get 'new'
        post 'create'
        get 'edit'
        patch 'update'
        get 'notes'
        patch 'addnotes'
        post 'grantadmin'
        post 'resetpassword'
        get 'holiday'
      end
    end
  end

  scope "vechicle_cost" do
    resources :vechicle_costs do
      member do
        get 'print_resume_month'
        get 'print_resume_year'
      end
    end
  end

end

app/models/application_record.rb
# model of Application class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
# model of Role class
class Role < ApplicationRecord
end

app/models/user.rb
# model of User class
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vechicle.rb
# model of Vechicle Param class
class Vechicle < ApplicationRecord
  has_many :vechicle_fuels

  def name_for_select
    "#{name} – #{plates}"
  end

  mount_uploader :photo, VechiclePhotoUploader
  mount_uploaders :attachments, VechicleAttachmentsUploader

end

app/models/vechicle_cost.rb
# model of Vechicle Cost class
class VechicleCost < ApplicationRecord
  belongs_to :user
  belongs_to :vechicle
end

app/models/vechicle_fuel.rb
# model of Vechicle Fuel class
class VechicleFuel < ApplicationRecord
  belongs_to :user
  belongs_to :vechicle
end

app/models/vechicle_note.rb
# model of Vechicle Note class
class VechicleNote < ApplicationRecord
  belongs_to :user
  belongs_to :vechicle
end

app/models/vechicle_param.rb
# model of Vechicle Param class
class VechicleParam < ApplicationRecord
  belongs_to :vechicle_param_type
  belongs_to :user
end

app/models/vechicle_param_type.rb
# model of Vechicle Param Type class
class VechicleParamType < ApplicationRecord
end

app/controllers/admin_controller.rb
# controller of Admin class
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def main
  end

  def users
    if params[:search].nil?
      @users = User.paginate(:page => params[:page], :per_page => 15)
    else
      @users = User.where(["department_id = ?", params[:search]]).paginate(:page => params[:page], :per_page => 1000)
      params[:search] = nil
    end
  end
end

app/controllers/pages_controller.rb
# controller of Pages class
class PagesController < ApplicationController
  before_filter :authenticate_user!, only:[:home]

  def home
  end
end

app/controllers/roles_controller.rb
# controller of Roles class
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Dodano uprawnienie.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Zmodyfikowano uprawnienie.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Usunięto uprawnienie.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :status)
    end
end

app/controllers/stats_controller.rb
# controller of Stats class
class StatsController < ApplicationController
  before_filter :authenticate_user!

  def main
  end

  def vechicles
    @vechicles = Vechicle.all
  end

  def costs
    @vechicle_costs = VechicleCost.all
  end

  def fuel
    @vechicle_fuels = VechicleFuel.all
  end

end

app/controllers/users_controller.rb
# controller of Users class
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def notes
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :back, notice: 'Użytkownik dodany.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params_edit)
        format.html { redirect_to :back, notice: 'Użytkownik zmodyfikowany.' }
      else
        format.html { render :edit }
      end
    end
  end

  def addnotes
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params_notes)
        format.html { redirect_to tickets_path, notice: 'Dodano notatke.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to admin_users_path, notice: "Użytkownik usunięty."
    end
  end

  def grantadmin
    @user = User.find(params[:id])
    user = User.find(@user.id)
    if @user.admin?
      user.update_attribute(:admin, false)
    else
      user.update_attribute(:admin, true)
    end
    redirect_to admin_users_path, notice: "Zakutalizowano uprawnienia administratora."
  end

  def resetpassword
    user = User.find(params[:id])
    user.password = "startowe"
    user.password_confirmation = "startowe"
    user.update_attribute(:sign_in_count, 0)
    user.save
    redirect_to admin_users_path, notice: "Zresetowano hasło."
  end

  def holiday
    @user = User.find(params[:id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :department_id, :role_id, :branch_id, :ceo, :proxy, :absence, :replacement, :division, :document_role_id, :division, :spec_role_id)
  end

  def user_params_edit
    params.require(:user).permit(:first_name, :last_name, :email, :department_id, :role_id, :branch_id, :document_role_id, :division, :spec_role_id, :sign_in_count, :proxy, :absence, :replacement)
  end

  def user_params_notes
    params.require(:user).permit(:notes)
  end

end

app/helpers/admin_helper.rb
# helper of Admin class
module AdminHelper
end

app/helpers/application_helper.rb
# helper of Application class
module ApplicationHelper
end

app/helpers/pages_helper.rb
# helper of Pages class
module PagesHelper
end

app/helpers/roles_helper.rb
# helper of Roles class
module RolesHelper
end

app/helpers/stats_helper.rb
# helper of Stats class
module StatsHelper
end

app/helpers/vechicles_helper.rb
# helper of Vechicles class
module VechiclesHelper
  require "#{Rails.root}/lib/calendar.rb"
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/admin/main.html.erb
<% content_for :title, "Panel Administracyjny" %>
<% content_for :menu, "admin" %>
<br>
<div class="container">
  <h1 class=page-header>Panel Administracyjny</h1>

  <h3 class=page-header>Statystyki</h3>
  <div class="row" align="center">
    <div class="col-md-4">
      <%= link_to 'Koszty', stats_costs_path, class:"btn btn-info" %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Paliwo', stats_fuel_path, class:"btn btn-info" %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Samochody', stats_vechicles_path, class:"btn btn-info" %>
    </div>
  </div>

  <h3 class=page-header>Ustawienia ogólne</h3>
  <div class="row" align="center">
    <div class="col-md-4">
      <%= link_to 'Użytkownicy', admin_users_path, class:'btn btn-danger' %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Uprawnienia ogólne', roles_path, class:'btn btn-warning' %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Rodzaje parametrów', vechicle_param_types_path, class:'btn btn-primary' %>
    </div>
  </div>

</div>
</br>

app/views/admin/users.html.erb
<% content_for :title, "Panel Administracyjny" %>
<% content_for :menu, "admin" %>
<div class="container">

<h1 class=page-header>Zarządzenie użytkownikami</h1>

<div class="row" align="center">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Login</th>
        <th>Admin?</th>
        <th>Logowanie</th>
        <th>Logowania</th>
        <th>Rejestracja</th>
        <th>Akcje</th>
      </tr>
    </thead>
    <tbody>
      <% @users.order("id").each do |user|  %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <% if user.admin == true %>
            <td>Tak</td>
          <% else %>
            <td>Nie</td>
          <% end %>
          <% if user.last_sign_in_at.nil? %>
            <td> Jeszcze się nie logował </td>
          <% else %>
            <td> <%= user.last_sign_in_at.strftime("%d.%m.%Y; %H:%M") if user.last_sign_in_at? %> </td>
          <% end %>
          <td><%= user.sign_in_count %></td>
          <td><%= user.created_at.strftime("%d.%m.%Y") if user.created_at? %></td>
          <td><%= link_to "Admin", grantadmin_user_path(user), method: :grantadmin, data: { confirm: "Jesteś pewny?" }, class:'btn btn-xs btn-warning'%>
          <%= link_to "Hasło", resetpassword_user_path(user), method: :resetpassword, data: { confirm: "Jesteś pewny?" }, class:'btn btn-xs btn-danger'%>
          <%= link_to "Edytuj", edit_user_path(user), class:'btn btn-xs btn-primary' %>
          <%= link_to "Usuń", user_path(user), method: :delete, data: { confirm: "Jesteś pewny?" }, class:'btn btn-xs btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p><%= will_paginate @users, renderer: FoundationPagination::Rails %></p>
</div>

<div class="row" align="center">
  <div class="callout" align="center">
    <%= link_to 'Nowy użytkownik', new_user_path, class:'btn btn-success' %>
  </div>
</div>

</div>

</br>

app/views/layouts/_header-admin.html.erb
<nav class="navbar navbar-inverse dontprint">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Panel Administracyjny</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Panel Administracyjny', admin_main_path, class:"navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href=/ title="Strona Główna">Strona Główna</a></li>
        <li><%= link_to "Użytkownicy", admin_users_path %></li>
        <li><%= link_to 'Uprawnienia', roles_path %></li>
        <li><%= link_to 'Rodzaje parametrów', vechicle_param_types_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Zalogowany jako #{User.where(id:current_user.id).pluck(:first_name).last} #{User.where(id:current_user.id).pluck(:last_name).last}", edit_user_registration_path, :title => "Zmiana hasła" %></li>
        <li><%= link_to 'Wyloguj', destroy_user_session_path, :title => "Wylogowanie ze systemu" %></li>
        <% else %>
        <li><%= link_to 'Zaloguj', new_user_session_path, :title => "Logowanie do systemu" %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse dontprint navbar-paliwko">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Paliwko – Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=/ title="Strona Główna">Paliwko</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Samochody", vechicles_path %></li>
        <li><%= link_to "Statystyki", stats_main_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Zaplecze", admin_main_path %></li>
        <li><%= link_to "Zalogowany jako #{User.where(id:current_user.id).pluck(:first_name).last} #{User.where(id:current_user.id).pluck(:last_name).last}", edit_user_registration_path, :title => "Zmiana hasła" %></li>
        <li><%= link_to 'Wyloguj', destroy_user_session_path, :title => "Wylogowanie ze systemu" %></li>
        <% else %>
        <li><%= link_to 'Zaloguj', new_user_session_path, :title => "Logowanie do systemu" %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-info container" role="alert">
    <button class="close" data-dismiss="alert">×</button>
    <%= content_tag :div, msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %> – Paliwko</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "jsapi", "chartkick" %>
  </head>

  <body>
    <% if yield(:menu) == "admin" %>
      <%= render 'layouts/header-admin' %>
    <% elsif yield(:menu) == "printer" %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
      <%= render partial: 'layouts/messages', flash: flash %>
    <%= yield %>
    <p align="center" class="dontprint" ><%= link_to "\u00A9 2017 kp-software.pl", pages_about_path, :title => "v2.3.3 z dnia 25.12.2017" %></p>
  </body>

</html>