config/routes.rb
Rails.application.routes.draw do
  resources :vechicle_params
  resources :vechicle_param_types
  resources :vechicle_fuels
  resources :vechicle_costs
  resources :vechicle_notes
  resources :vechicles
  resources :roles
  devise_for :users

  get 'pages/home'
  get 'pages/about'
  get 'admin/main'
  get 'admin/users'
  get 'stats/vechicles'
  get 'stats/costs'
  get 'stats/fuel'
  get 'stats/main'

  root 'pages#home'

  scope "vechicle" do
    resources :vechicles do
      member do
        get 'vechicle_parameters'
        get 'vechicle_fuels'
        get 'vechicle_costs'
      end
    end
  end

  scope "admin" do
    resources :users do
      member do
        delete 'destroy'
        get 'new'
        post 'create'
        get 'edit'
        patch 'update'
        get 'notes'
        patch 'addnotes'
        post 'grantadmin'
        post 'resetpassword'
        get 'holiday'
      end
    end
  end

  scope "vechicle_cost" do
    resources :vechicle_costs do
      member do
        get 'print_resume_month'
        get 'print_resume_year'
      end
    end
  end

end

app/models/vechicle_cost.rb
# model of Vechicle Cost class
class VechicleCost < ApplicationRecord
  belongs_to :user
  belongs_to :vechicle
end

app/controllers/vechicle_costs_controller.rb
# controller of Vechicle Costs class
class VechicleCostsController < ApplicationController
  before_action :set_vechicle_cost, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /vechicle_costs
  # GET /vechicle_costs.json
  def index
    @vechicle_costs = VechicleCost.all
  end

  # GET /vechicle_costs/1
  # GET /vechicle_costs/1.json
  def show
  end

  # GET /vechicle_costs/new
  def new
    @vechicle_cost = VechicleCost.new
  end

  # GET /vechicle_costs/1/edit
  def edit
  end

  # POST /vechicle_costs
  # POST /vechicle_costs.json
  def create
    @vechicle_cost = VechicleCost.new(vechicle_cost_params)

    respond_to do |format|
      if @vechicle_cost.save
        format.html { redirect_to @vechicle_cost, notice: 'Dodano koszt.' }
        format.json { render :show, status: :created, location: @vechicle_cost }
      else
        format.html { render :new }
        format.json { render json: @vechicle_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vechicle_costs/1
  # PATCH/PUT /vechicle_costs/1.json
  def update
    respond_to do |format|
      if @vechicle_cost.update(vechicle_cost_params)
        format.html { redirect_to @vechicle_cost, notice: 'Zmodyfikowano koszt.' }
        format.json { render :show, status: :ok, location: @vechicle_cost }
      else
        format.html { render :edit }
        format.json { render json: @vechicle_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vechicle_costs/1
  # DELETE /vechicle_costs/1.json
  def destroy
    @vechicle_cost.destroy
    respond_to do |format|
      format.html { redirect_to vechicle_costs_url, notice: 'Zmieniono koszt.' }
      format.json { head :no_content }
    end
  end

  def print_resume_month
    if params[:search].nil?
      @vechicle_costs = VechicleCost.all
    else
      vechicle = Vechicle.where(id:params[:search]).pluck(:id).last
      @vechicle_costs = VechicleCost.where(vechicle_id:vechicle)
      params[:search] = nil
    end
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @vechicle_costs = @vechicle_costs.where("to_char(created_at,'YYYY-MM') = ?", @date.strftime("%Y-%m"))
  end

  def print_resume_year
    if params[:search].nil?
      @vechicle_costs = VechicleCost.all
    else
      vechicle = Vechicle.where(id:params[:search]).pluck(:id).last
      @vechicle_costs = VechicleCost.where(vechicle_id:vechicle)
      params[:search] = nil
    end
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @vechicle_costs = @vechicle_costs.where("to_char(created_at,'YYYY') = ?", @date.strftime("%Y"))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vechicle_cost
      @vechicle_cost = VechicleCost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vechicle_cost_params
      params.require(:vechicle_cost).permit(:name, :user_id, :vechicle_id, :cost, :desc)
    end
end

app/helpers/vechicle_costs_helper.rb
# helper of Vechicle Costs class
module VechicleCostsHelper
end

app/views/vechicle_costs/_form.html.erb
<%= simple_form_for(@vechicle_cost) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="input-group">
      <span class="input-group-addon">Nazwa</span>
       <%= f.text_field :name, placeholder:"Nazwa", :autofocus => true, class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Samochód</span>
       <%= f.collection_select :vechicle_id, Vechicle.all.order("name"), :id, :name_for_select, {prompt: "Wybierz", id:"vachicleselect"}, {class:"form-control", required: true} %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Wartość</span>
       <%= f.number_field :cost, step:0.01, class:"form-control", required: true %><br>
      <span class="input-group-addon">zł</span>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Opis</span>
       <%= f.text_field :desc, placeholder:"Nazwa", :autofocus => true, class:"form-control", required: true %><br>
    </div><br>
  </div>

  <%= f.hidden_field :user, value:current_user.id %>
  <div align="center">
    <%= f.submit 'Zatwierdź', class:"btn btn-success" %>
    <%= link_to 'Lista kosztów', vechicle_costs_path, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/vechicle_costs/edit.html.erb
<h1>Editing Vechicle Cost</h1>

<%= render 'form', vechicle_cost: @vechicle_cost %>

<%= link_to 'Show', @vechicle_cost %> |
<%= link_to 'Back', vechicle_costs_path %>

app/views/vechicle_costs/index.html.erb
<% content_for :title, "Lista kosztów" %>
<div class="container">

<h1 class=page-header>Lista kosztów</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tytuł</th>
      <th>Pojazd</th>
      <th>Koszt [zł]</th>
      <th>Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicle_costs.each do |vechicle_cost| %>
      <tr>
        <td><%= vechicle_cost.name %></td>
        <td><%= Vechicle.where(id:vechicle_cost.vechicle_id).pluck(:plates).last %></td>
        <td><%= vechicle_cost.cost %></td>
        <td><%= link_to 'Przejdź', vechicle_cost, class:"btn btn-xs btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div align="center">
  <%= link_to 'Nowy koszt pojazdu', new_vechicle_cost_path, class:"btn btn-success" %>
  <%= link_to "Podsumowanie misięczne", print_resume_month_vechicle_cost_path(1), class:"btn btn-info" %>
  <%= link_to "Podsumowanie roczne", print_resume_year_vechicle_cost_path(1), class:"btn btn-info" %>
</div>

</div>
<br>

app/views/vechicle_costs/new.html.erb
<% content_for :title, "Nowy koszt" %>
<div class="container">

<h1 class=page-header>Nowy koszt</h1>

<%= render 'form', vechicle_cost: @vechicle_cost %>

</div>
<br>

app/views/vechicle_costs/print_resume_month.html.erb
<% content_for :title, "Lista kosztów samochodów" %>

<style type="text/css" media="print">
  .dontprint
  { display: none; }
</style>

<style type="text/css" media="screen">
  .dontwww
  { display: none; }
</style>

<div class="container">
<h3 class=page-header>Miesięczne koszty samochodu – <%= l(@date, format: :calendar).titleize %>.</h3>

<%= form_tag print_resume_month_vechicle_cost_path, :method => :get do %>
  <div class="input-group dontprint">
    <span class="input-group-addon">Urządzenie</span>
    <%= collection_select :search, params[:search], Vechicle.order("name"), :id, :name_for_select, {prompt: "Wybierz"}, class:"form-control", :onchange => "this.form.submit()" %>
  </div>
<% end %>
<br>
<div class="row" align="center">
  <div class="col-md-4 dontprint">
    <%= link_to print_resume_month_vechicle_cost_path(date: @date - 1.month), class: "btn btn-info" do %>
      <i class="fa-calendar-minus-o"> Poprzedni Miesiąc</i>
    <% end %>
  </div>
  <div class="col-md-4 dontprint">
    <h4 id="day"><%= l(@date, format: :calendar).titleize %></h4>
  </div>
  <div class="col-md-4 dontprint">
    <%= link_to print_resume_month_vechicle_cost_path(date: @date + 1.month), class: "btn btn-info" do %>
      <i class="fa-calendar-plus-o"> Następny Miesiąc</i>
    <% end %>
  </div>
</div>
<br>
<table style="width:100%" border="1" class="dontwww">
  <thead>
    <tr>
      <th>Samochód</th>
      <th>Autor</th>
      <th>Data</th>
      <th>Treść</th>
      <th>Koszt</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicle_costs.each do |vechicle_cost| %>
      <tr>
        <td><%= Vechicle.where(id:vechicle_cost.vechicle_id).pluck(:plates).last %></td>
        <td><%= User.where(id:vechicle_cost.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_cost.user_id).pluck(:last_name).last %></td>
        <td><%= vechicle_cost.created_at.strftime("%d.%m.%Y") if vechicle_cost.created_at? %></td>
        <td><%= link_to vechicle_cost.name, vechicle_cost %></td>
        <td><%= vechicle_cost.cost %> zł</td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="table dontprint">
  <thead>
    <tr>
      <th>Samochód</th>
      <th>Autor</th>
      <th>Data</th>
      <th>Treść</th>
      <th>Koszt</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicle_costs.each do |vechicle_cost| %>
      <tr>
        <td><%= Vechicle.where(id:vechicle_cost.vechicle_id).pluck(:plates).last %></td>
        <td><%= User.where(id:vechicle_cost.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_cost.user_id).pluck(:last_name).last %></td>
        <td><%= vechicle_cost.created_at.strftime("%d.%m.%Y") if vechicle_cost.created_at? %></td>
        <td><%= link_to vechicle_cost.name, vechicle_cost %></td>
        <td><%= vechicle_cost.cost %> zł</td>
      </tr>
    <% end %>
  </tbody>
</table>

<h6>Razem
    Kwota: <strong><%= @vechicle_costs.sum(:cost) %> zł </strong>
    Ilość: <strong><%= @vechicle_costs.count %></strong></h6>

<div class="dontprint" align="center">
  <%= link_to "Podsumowanie misięczne", print_resume_month_vechicle_cost_path(1), class:"btn btn-info" %>
  <%= link_to "Podsumowanie roczne", print_resume_year_vechicle_cost_path(1), class:"btn btn-info" %>
  <%= link_to "Lista Kosztów", vechicle_costs_path, class:"btn btn-primary" %>
  <%= link_to "Lista Samochodów", vechicles_path, class:"btn btn-primary" %>
  <a href="#" onclick="window.print();return false;" class="btn btn-success">Drukuj stronę</a>
</div>

</div>
<br>

app/views/vechicle_costs/print_resume_year.html.erb
<% content_for :title, "Lista kosztów samochodów" %>

<style type="text/css" media="print">
  .dontprint
  { display: none; }
</style>

<style type="text/css" media="screen">
  .dontwww
  { display: none; }
</style>

<div class="container">
<h3 class=page-header>Roczne koszty samochodu – <%= @date.strftime("%Y") %>.</h3>

<%= form_tag print_resume_month_vechicle_cost_path, :method => :get do %>
  <div class="input-group dontprint">
    <span class="input-group-addon">Urządzenie</span>
    <%= collection_select :search, params[:search], Vechicle.order("name"), :id, :name_for_select, {prompt: "Wybierz"}, class:"form-control", :onchange => "this.form.submit()" %>
  </div>
<% end %>
<br>
<div class="row" align="center">
  <div class="col-md-4 dontprint">
    <%= link_to print_resume_month_vechicle_cost_path(date: @date - 1.year), class: "btn btn-info" do %>
      <i class="fa-calendar-minus-o"> Poprzedni Miesiąc</i>
    <% end %>
  </div>
  <div class="col-md-4 dontprint">
    <h4 id="day"><%= l(@date, format: :calendar).titleize %></h4>
  </div>
  <div class="col-md-4 dontprint">
    <%= link_to print_resume_month_vechicle_cost_path(date: @date + 1.year), class: "btn btn-info" do %>
      <i class="fa-calendar-plus-o"> Następny Miesiąc</i>
    <% end %>
  </div>
</div>
<br>
<table style="width:100%" border="1" class="dontwww">
  <thead>
    <tr>
      <th>Samochód</th>
      <th>Autor</th>
      <th>Data</th>
      <th>Treść</th>
      <th>Koszt</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicle_costs.each do |vechicle_cost| %>
      <tr>
        <td><%= Vechicle.where(id:vechicle_cost.vechicle_id).pluck(:plates).last %></td>
        <td><%= User.where(id:vechicle_cost.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_cost.user_id).pluck(:last_name).last %></td>
        <td><%= vechicle_cost.created_at.strftime("%d.%m.%Y") if vechicle_cost.created_at? %></td>
        <td><%= link_to vechicle_cost.name, vechicle_cost %></td>
        <td><%= vechicle_cost.cost %> zł</td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="table dontprint">
  <thead>
    <tr>
      <th>Samochód</th>
      <th>Autor</th>
      <th>Data</th>
      <th>Treść</th>
      <th>Koszt</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicle_costs.each do |vechicle_cost| %>
      <tr>
        <td><%= Vechicle.where(id:vechicle_cost.vechicle_id).pluck(:plates).last %></td>
        <td><%= User.where(id:vechicle_cost.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_cost.user_id).pluck(:last_name).last %></td>
        <td><%= vechicle_cost.created_at.strftime("%d.%m.%Y") if vechicle_cost.created_at? %></td>
        <td><%= link_to vechicle_cost.name, vechicle_cost %></td>
        <td><%= vechicle_cost.cost %> zł</td>
      </tr>
    <% end %>
  </tbody>
</table>

<h6>Razem
    Kwota: <strong><%= @vechicle_costs.sum(:cost) %> zł </strong>
    Ilość: <strong><%= @vechicle_costs.count %></strong></h6>

<div class="dontprint" align="center">
  <%= link_to "Podsumowanie misięczne", print_resume_month_vechicle_cost_path(1), class:"btn btn-info" %>
  <%= link_to "Podsumowanie roczne", print_resume_year_vechicle_cost_path(1), class:"btn btn-info" %>
  <%= link_to "Lista Samochodów", vechicles_path, class:"btn btn-primary" %>
  <a href="#" onclick="window.print();return false;" class="btn btn-success">Drukuj stronę</a>
</div>

</div>
<br>

app/views/vechicle_costs/show.html.erb
<% content_for :title, "Koszt" %>
<div class="container">

<h1 class=page-header>Koszt</h1>

<p>Nazwa: <strong><%= @vechicle_cost.name %></strong></p>
<p>Autor: <strong><%= User.where(id:@vechicle_cost.user_id).pluck(:first_name).last %>
          <%= User.where(id:@vechicle_cost.user_id).pluck(:last_name).last %></strong></p>
<p>Samochód: <strong><%= Vechicle.where(id:@vechicle_cost.vechicle_id).pluck(:plates).last %></strong></p>
<p>Wartość: <strong><%= @vechicle_cost.cost %>zł</strong></p>
<p>Opis: <strong><%= @vechicle_cost.desc %></strong></p>

<div align="center">
  <%= link_to 'Edytuj', edit_vechicle_cost_path(@vechicle_cost), class:"btn btn-warning" %>
  <%= link_to 'Lista kosztów', vechicle_costs_path, class:"btn btn-primary" %>
  <%= link_to 'Powrót do samochodu', vechicle_path(@vechicle_cost.vechicle_id), class:"btn btn-default" %>
</div>

</div>
<br>