config/routes.rb
Rails.application.routes.draw do
  resources :vechicle_params
  resources :vechicle_param_types
  resources :vechicle_fuels
  resources :vechicle_costs
  resources :vechicle_notes
  resources :vechicles
  resources :roles
  devise_for :users

  get 'pages/home'
  get 'pages/about'
  get 'admin/main'
  get 'admin/users'
  get 'stats/vechicles'
  get 'stats/costs'
  get 'stats/fuel'
  get 'stats/main'

  root 'pages#home'

  scope "vechicle" do
    resources :vechicles do
      member do
        get 'vechicle_parameters'
        get 'vechicle_fuels'
        get 'vechicle_costs'
      end
    end
  end

  scope "admin" do
    resources :users do
      member do
        delete 'destroy'
        get 'new'
        post 'create'
        get 'edit'
        patch 'update'
        get 'notes'
        patch 'addnotes'
        post 'grantadmin'
        post 'resetpassword'
        get 'holiday'
      end
    end
  end

  scope "vechicle_cost" do
    resources :vechicle_costs do
      member do
        get 'print_resume_month'
        get 'print_resume_year'
      end
    end
  end

end

app/models/vechicle_fuel.rb
# model of Vechicle Fuel class
class VechicleFuel < ApplicationRecord
  belongs_to :user
  belongs_to :vechicle
end

app/controllers/vechicle_fuels_controller.rb
# controller of Vechicle Fules class
class VechicleFuelsController < ApplicationController
  before_action :set_vechicle_fuel, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /vechicle_fuels
  # GET /vechicle_fuels.json
  def index
    @vechicle_fuels = VechicleFuel.all
  end

  # GET /vechicle_fuels/1
  # GET /vechicle_fuels/1.json
  def show
  end

  # GET /vechicle_fuels/new
  def new
    @vechicle_fuel = VechicleFuel.new
  end

  # GET /vechicle_fuels/1/edit
  def edit
  end

  # POST /vechicle_fuels
  # POST /vechicle_fuels.json
  def create
    @vechicle_fuel = VechicleFuel.new(vechicle_fuel_params)

    respond_to do |format|
      if @vechicle_fuel.save
        fuel_number
        create_cost
        fuel_consumption
        update_mileage
        format.html { redirect_to @vechicle_fuel, notice: 'Dodano tankowanie.' }
        format.json { render :show, status: :created, location: @vechicle_fuel }
      else
        format.html { render :new }
        format.json { render json: @vechicle_fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vechicle_fuels/1
  # PATCH/PUT /vechicle_fuels/1.json
  def update
    respond_to do |format|
      if @vechicle_fuel.update(vechicle_fuel_params)
        format.html { redirect_to @vechicle_fuel, notice: 'Zmodyfikowano tankowanie.' }
        format.json { render :show, status: :ok, location: @vechicle_fuel }
      else
        format.html { render :edit }
        format.json { render json: @vechicle_fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vechicle_fuels/1
  # DELETE /vechicle_fuels/1.json
  def destroy
    @vechicle_fuel.destroy
    respond_to do |format|
      format.html { redirect_to vechicle_fuels_url, notice: 'Usunięto tankowanie.' }
      format.json { head :no_content }
    end
  end

  def fuel_number
    @number = VechicleFuel.order(:id).pluck(:number).second_to_last.to_i
    VechicleFuel.update(@vechicle_fuel.id, :number => @number+1)
  end

  def create_cost
    cost = @vechicle_fuel.cost
    user_id = current_user.id
    name = "Paliwo"
    vechicle_id = @vechicle_fuel.vechicle_id
    @vechicle_cost = VechicleCost.new(user_id:user_id, vechicle_id:vechicle_id, cost:cost, name:name)
    @vechicle_cost.save
  end

  def update_mileage
    Vechicle.update(@vechicle_fuel.vechicle_id, :mileage => @vechicle_fuel.mileage)
  end

  def fuel_consumption
    @mileage = Vechicle.where(id:@vechicle_fuel.vechicle_id).pluck(:mileage).last
    @mileage_delta = @vechicle_fuel.mileage.to_i - @mileage.to_i
    @fuel = @vechicle_fuel.value.to_f
    @consumption = ((@fuel.to_f/@mileage_delta.to_i)*100).round(2).to_f
    VechicleFuel.update(@vechicle_fuel.id, :consumption => @consumption)
    VechicleFuel.update(@vechicle_fuel.id, :mileage_delta => @mileage_delta)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vechicle_fuel
      @vechicle_fuel = VechicleFuel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vechicle_fuel_params
      params.require(:vechicle_fuel).permit(:company, :user_id, :vechicle_id, :value, :mileage, :desc, :cost, :number, :consumption, :mileage_delta)
    end
end

app/helpers/vechicle_fuels_helper.rb
# helper of Vechicle Fules class
module VechicleFuelsHelper
end

app/views/vechicle_fuels/_form.html.erb
<%= simple_form_for(@vechicle_fuel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="input-group">
      <span class="input-group-addon">Samochód</span>
        <% if params[:vid].nil? %>
          <%= f.collection_select :vechicle_id, Vechicle.all.order("name"), :id, :name_for_select, {prompt: "Wybierz", id:"vachicleselect"}, {class:"form-control", required: true} %>
        <% else %>
          <%= f.text_field :vechicle_id, :value => "#{Vechicle.where(id:params[:vid]).pluck(:name).last} – #{Vechicle.where(id:params[:vid]).pluck(:plates).last}", :readonly => true, class:"form-control" %>
          <%= f.hidden_field :vechicle_id, :value => params[:vid] %>
        <% end %>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Stacja</span>
       <%= f.text_field :company, placeholder:"Nazwa stacji paliw", :autofocus => true, class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Ilość</span>
       <%= f.number_field :value, min:1, placeholder:"Ilość zatankowanego paliwa wyrażona w litrach", class:"form-control", required: true %><br>
      <span class="input-group-addon">l</span>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Koszt</span>
       <%= f.number_field :cost, min:1, placeholder:"Koszt zatankowanego paliwa wyrażona w złotówkach", class:"form-control", required: true %><br>
      <span class="input-group-addon">zł</span>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Przebieg</span>
       <%= f.number_field :mileage, min:1, placeholder:"Wartość licznika tuż przed tankowaniem wyrażona w kilometrach", class:"form-control", required: true %><br>
      <span class="input-group-addon">km</span>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Uwagi(opcjonalnie)</span>
       <%= f.text_field :desc, placeholder:"Uwagi i notatki do tankowania, wypełniamy opcjonalnie", class:"form-control", required: true %><br>
    </div><br>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div align="center">
    <%= f.submit "Zatwierdź", class:"btn btn-success" %>
    <%= link_to 'Lista tankowań', vechicle_fuels_path, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/vechicle_fuels/edit.html.erb
<% content_for :title, "Edycja tankowania" %>

<div class="container">

<h1 class=page-header>Edycja tankowania</h1>

<%= render 'form', vechicle_fuel: @vechicle_fuel %>

</div>

app/views/vechicle_fuels/index.html.erb
<% content_for :title, "Lista tankowań" %>
<div class="container">

<h1 class=page-header>Lista tankowań</h1>

<table class="table">
  <thead>
    <tr>
      <th>Stacja</th>
      <th>Samochód</th>
      <th>Ilość[l]</th>
      <th>Koszt[zł]</th>
      <th>Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicle_fuels.each do |vechicle_fuel| %>
      <tr>
        <td><%= vechicle_fuel.company %></td>
        <td><%= Vechicle.where(id:vechicle_fuel.vechicle_id).pluck(:plates).last %></td>
        <td><%= vechicle_fuel.value %></td>
        <td><%= vechicle_fuel.cost %></td>
        <td><%= link_to 'Przejdź', vechicle_fuel, class:"btn btn-xs btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div align="center">
  <%= link_to 'Nowe tankowanie', new_vechicle_fuel_path, class:"btn btn-success" %>
</div>

</div>

app/views/vechicle_fuels/new.html.erb
<% content_for :title, "Nowe tankowanie" %>

<div class="container">

<h1 class=page-header>Nowe tankowanie</h1>

<%= render 'form', vechicle_fuel: @vechicle_fuel %>

</div>
<br>

app/views/vechicle_fuels/show.html.erb
<% content_for :title, "Tankowanie" %>

<div class="container">

<h1 class=page-header>Tankowanie nr <%= @vechicle_fuel.number %></h1>

<p>Stacja paliw: <strong><%= @vechicle_fuel.company %></strong></p>
<p>Autor wpisu: <strong><%= User.where(id:@vechicle_fuel.user_id).pluck(:first_name).last %>
          <%= User.where(id:@vechicle_fuel.user_id).pluck(:last_name).last %></strong></p>
<p>Samochód: <strong><%= Vechicle.where(id:@vechicle_fuel.vechicle_id).pluck(:plates).last %></strong></p>
<p>Ilość: <strong><%= @vechicle_fuel.value %>l</strong></p>
<p>Koszt: <strong><%= @vechicle_fuel.cost %>zł</strong></p>
<p>Cena za litr: <strong><%= (@vechicle_fuel.cost.to_f/@vechicle_fuel.value.to_f) %>zł</strong></p>
<p>Przebieg: <strong><%= @vechicle_fuel.mileage %>km</strong></p>
<p>Różnica przebiegu: <strong><%= @vechicle_fuel.mileage_delta %>km</strong></p>
<p>Spalanie: <strong><%= @vechicle_fuel.consumption %>l na 100km</strong></p>
<p>Uwagi: <strong><%= @vechicle_fuel.desc if @vechicle_fuel.desc %>
          <%= "Brak" unless @vechicle_fuel.desc %></strong></p>

<div align="center">
  <%= link_to 'Edycja wpisu', edit_vechicle_fuel_path(@vechicle_fuel), class:"btn btn-warning" %>
  <%= link_to 'Lista tankowań', vechicle_fuels_path, class:"btn btn-primary" %>
  <%= link_to 'Przejdź do samochodu', vechicle_path(@vechicle_fuel.vechicle_id), class:"btn btn-default" %>
</div>

</div>
<br>