config/routes.rb
Rails.application.routes.draw do
  resources :vechicle_params
  resources :vechicle_param_types
  resources :vechicle_fuels
  resources :vechicle_costs
  resources :vechicle_notes
  resources :vechicles
  resources :roles
  devise_for :users

  get 'pages/home'
  get 'pages/about'
  get 'admin/main'
  get 'admin/users'
  get 'stats/vechicles'
  get 'stats/costs'
  get 'stats/fuel'
  get 'stats/main'

  root 'pages#home'

  scope "vechicle" do
    resources :vechicles do
      member do
        get 'vechicle_parameters'
        get 'vechicle_fuels'
        get 'vechicle_costs'
      end
    end
  end

  scope "admin" do
    resources :users do
      member do
        delete 'destroy'
        get 'new'
        post 'create'
        get 'edit'
        patch 'update'
        get 'notes'
        patch 'addnotes'
        post 'grantadmin'
        post 'resetpassword'
        get 'holiday'
      end
    end
  end

  scope "vechicle_cost" do
    resources :vechicle_costs do
      member do
        get 'print_resume_month'
        get 'print_resume_year'
      end
    end
  end

end

app/models/vechicle.rb
# model of Vechicle Param class
class Vechicle < ApplicationRecord
  has_many :vechicle_fuels

  def name_for_select
    "#{name} – #{plates}"
  end

  mount_uploader :photo, VechiclePhotoUploader
  mount_uploaders :attachments, VechicleAttachmentsUploader

end

app/controllers/vechicles_controller.rb
# controller of Vechicles class
class VechiclesController < ApplicationController
  before_action :set_vechicle, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /vechicles
  # GET /vechicles.json
  def index
    @vechicles = Vechicle.all
  end

  # GET /vechicles/1
  # GET /vechicles/1.json
  def show
    @vechicle_notes = VechicleNote.all
    @vechicle_costs = VechicleCost.all
    @vechicle_fuels = VechicleFuel.all
  end

  # GET /vechicles/new
  def new
    @vechicle = Vechicle.new
  end

  # GET /vechicles/1/edit
  def edit
  end

  # POST /vechicles
  # POST /vechicles.json
  def create
    @vechicle = Vechicle.new(vechicle_params)

    respond_to do |format|
      if @vechicle.save
        format.html { redirect_to @vechicle, notice: 'Dodano samochód.' }
        format.json { render :show, status: :created, location: @vechicle }
      else
        format.html { render :new }
        format.json { render json: @vechicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vechicles/1
  # PATCH/PUT /vechicles/1.json
  def update
    respond_to do |format|
      if @vechicle.update(vechicle_params)
        format.html { redirect_to @vechicle, notice: 'Zmodyfikowano samochód.' }
        format.json { render :show, status: :ok, location: @vechicle }
      else
        format.html { render :edit }
        format.json { render json: @vechicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vechicles/1
  # DELETE /vechicles/1.json
  def destroy
    @vechicle.destroy
    respond_to do |format|
      format.html { redirect_to vechicles_url, notice: 'Usunięto samochód.' }
      format.json { head :no_content }
    end
  end

  def vechicle_parameters
    @vechicle = Vechicle.find(params[:id])
    @vechicle_params = VechicleParam.where(vechicle_id:@vechicle.id)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @vechicle_params = @vechicle_params.paginate(:page => params[:page], :per_page => 10)
  end

  def vechicle_fuels
    @vechicle = Vechicle.find(params[:id])
    @vechicle_fuels = VechicleFuel.where(vechicle_id:@vechicle.id)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @vechicle_fuels = @vechicle_fuels.paginate(:page => params[:page], :per_page => 10)
  end

  def vechicle_costs
    @vechicle = Vechicle.find(params[:id])
    @vechicle_costs = VechicleCost.where(vechicle_id:@vechicle.id)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @vechicle_costs = @vechicle_costs.paginate(:page => params[:page], :per_page => 10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vechicle
      @vechicle = Vechicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vechicle_params
      params.require(:vechicle).permit(:name, :plates, :productiondate, :registration, :lastrevision, :nextrevison, :desc, :mileage, :photo, {attachments: []}, :status)
    end
end

app/helpers/vechicles_helper.rb
# helper of Vechicles class
module VechiclesHelper
  require "#{Rails.root}/lib/calendar.rb"
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/vechicles/_form.html.erb
<%= simple_form_for(@vechicle) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="input-group">
      <span class="input-group-addon">Nazwa</span>
       <%= f.text_field :name, placeholder:"Nazwa", :autofocus => true, class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Tablice rejestracyjne</span>
       <%= f.text_field :plates, placeholder:"GKS", class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Data produkcji</span>
       <%= f.text_field :productiondate, type:"date", class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Data rejetracji</span>
       <%= f.text_field :registration, type:"date", class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Data osatatniego przeglądu</span>
       <%= f.text_field :lastrevision, type:"date", class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Data następnego przeglądu</span>
       <%= f.text_field :nextrevison, type:"date", class:"form-control", required: true %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Przebieg</span>
       <%= f.number_field :mileage, class:"form-control", required: true %><br>
      <span class="input-group-addon">km</span>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Krótki Opis</span>
       <%= f.text_area :desc, placeholder:"Krótki Opis", class:"form-control", rows:"3" %><br>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Ilustracja</span>
       <%= f.file_field :photo, class:"form-control" %>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon">Pliki/Dokumentacja</span>
      <%= f.file_field :attachments, multiple: true, class:"form-control" %>
   </div><br>
  </div>

  <div align="center">
    <%= f.submit 'Zatwierdź', class:"btn btn-success" %>
    <%= link_to 'Lista pojazdów', vechicles_path, class:"btn btn-primary" %>
  </div>

<% end %>

app/views/vechicles/edit.html.erb
<% content_for :title, "Edytuj pojazd" %>

<div class="container">

<h1 class=page-header>Edytuj pojazd</h1>

<%= render 'form', vechicle: @vechicle %>

</div>
<br>

app/views/vechicles/index.html.erb
<% content_for :title, "Lista pojazdów" %>

<div class="container">

<h1 class=page-header>Lista pojazdów</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Tablice</th>
      <th>Przebieg</th>
      <th>Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @vechicles.each do |vechicle| %>
      <tr>
        <td><%= vechicle.name %></td>
        <td><%= vechicle.plates %></td>
        <td><%= vechicle.mileage %> km</td>
        <td><%= link_to "Przejdź", vechicle, class:"btn btn-xs btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div align="center">
  <%= link_to 'Nowy samochód', new_vechicle_path, class:"btn btn-success" %>
</div>
</div>
<br>

app/views/vechicles/new.html.erb
<% content_for :title, "Nowy pojazd" %>

<div class="container">
  
  <h1 class=page-header>Nowy pojazd</h1>

  <%= render 'form', vechicle: @vechicle %>

</div>
<br>

app/views/vechicles/show.html.erb
<% content_for :title, "Lista samochodów" %>

<div class="container">

<h1 class=page-header><%= @vechicle.name %></h1>

<div class="row">
  <div class="col-md-8" align="left">
    <p>Tablice rejestracyjne: <strong><%= @vechicle.plates %></strong></p>
    <p>Data produkcji: <strong><%= @vechicle.productiondate %></strong></p>
    <p>Data rejestracji: <strong><%= @vechicle.registration %></strong></p>
    <p>Ostatni przegląd: <strong><%= @vechicle.lastrevision %></strong></p>
    <p>Następny przegląd: <strong><%= @vechicle.nextrevison %></strong></p>
    <p>Opis: <strong><%= @vechicle.desc %></strong></p>
    <p>Przebieg: <strong><%= @vechicle.mileage %> km</strong></p>
    <p>Spalanie z ostatniego tankowania: <strong><%= VechicleFuel.where(vechicle_id:@vechicle.id).pluck(:consumption).last %>l na 100km</strong></p>
    <p>
      <%= link_to 'Edycja pojazdu', edit_vechicle_path(@vechicle), class:"btn btn-warning" %>
      <%= link_to 'Lista pojazdów', vechicles_path, class:"btn btn-primary" %>
    </p>
    <p>
      <%= link_to 'Parametry', vechicle_parameters_vechicle_path(id:@vechicle.id, date: @date), class:"btn btn-info" %>
      <%= link_to 'Tankowania', vechicle_fuels_vechicle_path(id:@vechicle.id), class:"btn btn-info" %>
      <%= link_to 'Koszty', vechicle_costs_vechicle_path(id:@vechicle.id), class:"btn btn-info" %>
    </p>
  </div>
  <div class="col-md-4" align="center">
    <% if @vechicle.photo? %>
      <%= link_to( image_tag(@vechicle.photo.url(:thumb)), @vechicle.photo.url) %>
      <p align="center"><i>kliknij, aby powiększyć</i></p>
    <% else %>
      <p align="center"><i>brak ilustracji</i></p>
    <% end %>
    <h4 class=page-header>Załączniki</h4>
    <% if @vechicle.attachments? %>
      <% @vechicle.attachments.each_with_index do |attach, index| %>
        <p><%= link_to File.basename(attach.url), attach.url %></p
      <% end %>
    <% else %>
      <p align="center"><i>brak załączników</i></p>
    <% end %>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <h4 id="comments"> Notatki do pojazdu </h4>
    <table class="table">
      <thead>
        <tr>
          <th>Autor</th>
          <th>Data</th>
          <th>Treść</th>
        </tr>
      </thead>
      <tbody>
        <% @vechicle_notes.each do |vechicle_note| %>
        <% if @vechicle.id == VechicleNote.where(id:vechicle_note.vechicle_id).pluck(:id).last %>
          <tr>
            <td><%= User.where(id:vechicle_note.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_note.user_id).pluck(:last_name).last %></td>
            <td><%= vechicle_note.created_at.strftime("%d.%m.%Y") if vechicle_note.created_at?%></td>
            <td><%= vechicle_note.name %></td>
          </tr>
        <% end %><% end %>
      </tbody>
    </table>
      <%= form_for VechicleNote.new do |f| %>
        <%= f.hidden_field :vechicle_id, :value => @vechicle.id  %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <div class="col-md-12">
        <div class="input-group">
          <span class="input-group-addon">Treść</span>
            <%= f.text_field :name, type:"text", placeholder:"Treść notatki", class:"form-control", required: true %>
          <span class="input-group-btn">
              <%= f.submit "Dodaj notatkę", class:"btn btn-success" %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

</div>
<br>

app/views/vechicles/vechicle_costs.html.erb
<% content_for :title, "Koszty" %>

<div class="container">
  <h1 class="page-header"><%= "#{@vechicle.name} #{@vechicle.plates}" %>
      <%= link_to "Powrót do samochodu", vechicle_path(@vechicle.id), class:"btn btn-sm btn-primary" %></h1>

  <h4 class="page-header">Nowy koszt</h4>
    <%= form_for VechicleCost.new do |f| %>
      <%= f.hidden_field :vechicle_id, :value => @vechicle.id  %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="col-md-12">
      <div class="input-group">
        <span class="input-group-addon">Treść</span>
          <%= f.text_field :name, type:"text", placeholder:"Opis kosztu", class:"form-control", required: true %>
        <span class="input-group-addon">Koszt</span>
          <%= f.number_field :cost, type:"text", min:0, placeholder:"Koszt w złotówkach", class:"form-control", required: true %>
        <span class="input-group-btn">
            <%= f.submit "Dodaj koszt", class:"btn btn-success" %>
        </span>
      </div>
    </div>
  <% end %>
<br>

  <h4 class="page-header">Lista kosztów</h4>
  <div class="row" align="center">
    <div class="col-md-4">
      <%= link_to vechicle_costs_vechicle_path(date: @date - 1.month), class: "btn btn-info" do %>
        <i class="fa-calendar-minus-o"> Poprzedni Miesiąc</i>
      <% end %>
    </div>
    <div class="col-md-4">
      <h4 id="day"><%= l(@date, format: :calendar).titleize %></h4>
    </div>
    <div class="col-md-4">
      <%= link_to vechicle_costs_vechicle_path(date: @date + 1.month), class: "btn btn-info" do %>
        <i class="fa-calendar-plus-o"> Następny Miesiąc</i>
      <% end %>
    </div>
  </div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>Autor</th>
        <th>Data</th>
        <th>Treść</th>
        <th>Koszt</th>
      </tr>
    </thead>
    <tbody>
      <% @vechicle_costs.order("created_at desc").each do |vechicle_cost| %>
        <% if vechicle_cost.created_at %>
          <% if @date.strftime("%Y-%m-%d") == vechicle_cost.created_at.strftime("%Y-%m-%d") %>
          <tr>
            <td><%= User.where(id:vechicle_cost.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_cost.user_id).pluck(:last_name).last %></td>
            <td><%= vechicle_cost.created_at.strftime("%d.%m.%Y") if vechicle_cost.created_at? %></td>
            <td><%= link_to vechicle_cost.name, vechicle_cost %></td>
            <td><%= vechicle_cost.cost %> zł</td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div align="center">
    <p><%= will_paginate @vechicle_costs, renderer: BootstrapPagination::Rails %></p>
  </div>
</div>
</div>
</br>

app/views/vechicles/vechicle_fuels.html.erb
<% content_for :title, "Tankowania" %>

<div class="container">
  <h1 class="page-header"><%= "#{@vechicle.name} #{@vechicle.plates}" %>
      <%= link_to "Powrót do samochodu", vechicle_path(@vechicle.id), class:"btn btn-sm btn-primary" %></h1>

  <h4 class="page-header">Nowe tankowanie</h4>
  <div class="row" align="center">
    <div class="col-md-12">
      <%= link_to 'Dodaj tankowanie', new_vechicle_fuel_path(vid:@vechicle.id), class:"btn btn-success" %>
    </div>
  </div>
  <br>

  <h4 class="page-header">Lista tankowań</h4>
  <div class="row" align="center">
    <div class="col-md-4">
      <%= link_to vechicle_fuels_vechicle_path(date: @date - 1.month), class: "btn btn-info" do %>
        <i class="fa-calendar-minus-o"> Poprzedni Miesiąc</i>
      <% end %>
    </div>
    <div class="col-md-4">
      <h4 id="day"><%= l(@date, format: :calendar).titleize %></h4>
    </div>
    <div class="col-md-4">
      <%= link_to vechicle_fuels_vechicle_path(date: @date + 1.month), class: "btn btn-info" do %>
        <i class="fa-calendar-plus-o"> Następny Miesiąc</i>
      <% end %>
    </div>
  </div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>Autor</th>
        <th>Data</th>
        <th>Tablice</th>
        <th>Ilość[l]</th>
        <th>Koszt[zł]</th>
      </tr>
    </thead>
    <tbody>
      <% @vechicle_fuels.order("created_at desc").each do |vechicle_fuel| %>
        <% if vechicle_fuel.created_at %>
          <% if @date.strftime("%Y-%m") == vechicle_fuel.created_at.strftime("%Y-%m") %>
          <tr>
            <td><%= User.where(id:vechicle_fuel.user_id).pluck(:first_name).last %> <%= User.where(id:vechicle_fuel.user_id).pluck(:last_name).last %></td>
            <td><%= vechicle_fuel.created_at.strftime("%d.%m.%Y") if vechicle_fuel.created_at?%></td>
            <td><%= Vechicle.where(id:vechicle_fuel.vechicle_id).pluck(:plates).last %></td>
            <td><%= vechicle_fuel.value %></td>
            <td><%= vechicle_fuel.cost %></td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div align="center">
    <p><%= will_paginate @vechicle_fuels, renderer: BootstrapPagination::Rails %></p>
  </div>
</div>
</div>
</br>

app/views/vechicles/vechicle_parameters.html.erb
<% content_for :title, "Parametry" %>

<div class="container">
  <h1 class="page-header"><%= "#{@vechicle.name} #{@vechicle.plates}" %>
      <%= link_to "Powrót do samochodu", vechicle_path(@vechicle.id), class:"btn btn-sm btn-primary" %></h1>

  <h4 class="page-header">Nowy parametr</h4>
    <%= form_for VechicleParam.new do |f| %>
      <%= f.hidden_field :vechicle_id, :value => @vechicle.id  %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="col-md-12">
        <div class="input-group">
          <span class="input-group-addon">Rodzaj</span>
          <%= f.collection_select :vechicle_param_type_id, VechicleParamType.all, :id, :name, {prompt: "Wybierz"}, {class:"form-control", required: true} %>
          <span class="input-group-addon">Wartość</span>
            <%= f.number_field :value, :step => 0.1, :min => 0, class:"form-control", required: true %>
          <span class="input-group-addon">Uwagi</span>
            <%= f.text_field :desc, class:"form-control" %>
          <span class="input-group-btn">
            <%= f.submit "Zatwierdź", class:"btn btn-success" %>
          </span>
        </div>
      </div>
  <% end %>
  <br>

  <h4 class="page-header">Lista parametrów</h4>
  <div class="row" align="center">
    <div class="col-md-4">
      <%= link_to vechicle_parameters_vechicle_path(date: @date - 1.day), class: "btn btn-info" do %>
        <i class="fa-calendar-minus-o"> Poprzedni Dzień</i>
      <% end %>
    </div>
    <div class="col-md-4">
      <h4 id="day"><%= @date %></h4>
    </div>
    <div class="col-md-4">
      <%= link_to vechicle_parameters_vechicle_path(date: @date + 1.day), class: "btn btn-info" do %>
        <i class="fa-calendar-plus-o"> Następny Dzień</i>
      <% end %>
    </div>
  </div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>Rodzaj</th>
        <th>Wartosć</th>
        <th>Data i czas</th>
        <th>Autor</th>
      </tr>
    </thead>
    <tbody>
      <% @vechicle_params.order("created_at desc").each do |vechicle_param| %>
        <% if vechicle_param.created_at %>
          <% if @date.strftime("%Y-%m-%d") == vechicle_param.created_at.strftime("%Y-%m-%d") %>
          <tr>
            <td><%= VechicleParamType.where(id:vechicle_param.vechicle_param_type).pluck(:name).last %></td>
            <td><%= link_to vechicle_param.value, vechicle_param, title:vechicle_param.desc %></td>
            <td><%= vechicle_param.created_at.strftime("%d.%m.%Y, %H:%M") if vechicle_param.created_at? %></td>
            <td><%= "#{User.where(id:vechicle_param.user_id).pluck(:first_name).last[0]}#{User.where(id:vechicle_param.user_id).pluck(:last_name).last[0]}"%></td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div align="center">
    <p><%= will_paginate @vechicle_params, renderer: BootstrapPagination::Rails %></p>
  </div>
</div>
</div>
</br>